# Generated by Django 4.0.4 on 2022-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlentry',
            name='shortened_url',
            field=models.URLField(default='gg', max_length=30),
            preserve_default=False,
        ),
    ]
