# Generated by Django 4.0.4 on 2022-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortIt', '0003_alter_urlentry_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='shortened_url',
            field=models.URLField(max_length=30),
        ),
    ]
